name: Continuous integration with github

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install dos2unix
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Grant execute permission and convert EOL for gradlew
        run: |
          chmod +x ./gradlew
          dos2unix ./gradlew

      - name: Check gradlew permissions
        run: ls -l ./gradlew

      - name: Build and clean project
        run: ./gradlew clean build --warning-mode all --stacktrace --info

      - name: Run all tests
        run: ./gradlew test --stacktrace --info

      - name: Create .jar and install
        run: ./gradlew bootJar --stacktrace --info

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dos2unix
        run: |
          sudo apt-get update
          sudo apt-get install -y dos2unix

      - name: Grant execute permission and convert EOL for gradlew
        run: |
          chmod +x ./gradlew
          dos2unix ./gradlew

      - name: Check gradlew permissions
        run: ls -l ./gradlew

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0



